version: '3'
services:
  #Nginx Service
  webserver_env:
    image: shiphp/nginx-env
    container_name: ${NGINX_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - "70:80"
      - "470:443"
    volumes:
      - ${PROJECT_CODE}:/var/www
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/nginx.conf:/etc/nginx/nginx.conf
    #command: ["/usr/local/bin/start.sh"]
    environment:
      NGINX_HOST: ${NGINX_HOST}
    env_file:
      - .env
#Docker Networks
networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
