version: '3'
services:
  db:
    image: harbor.jucce.cn/god/mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: test
      MYSQL_USER: mark
      MYSQL_PASSWORD:
    volumes:
      - ${PROJECT_ROOT}/configs/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: harbor.jucce.cn/god/adminer:latest
    restart: always
    ports:
      - 8084:8080
  phpmyadmin:
    image: harbor.jucce.cn/god/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
networks:
  default:
    external:
      name: ${NETWORK:-webproxy}