version: '3'
services:
  jenkins:
    image: harbor.jucce.cn/god/jenkins_lts
    restart: always
    volumes:
      - ${PROJECT_ROOT}/configs/jenkins/jenkins_home:/var/jenkins_home
    environment:
      - VIRTUAL_HOST=jenkins.jucce.cn
      - VIRTUAL_NETWORK=webproxy
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=jenkins.jucce.cn
      - LETSENCRYPT_EMAIL=juccexu@gmail.com
networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
