version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - 8083:8080
      - 50003:50000
    volumes:
      - ${PROJECT_ROOT}/configs/jenkins/jenkins_home:/var/jenkins_home
networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
