version: '3'
services:
  web:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    container_name: gitlab-runner
    volumes:
      - ${PROJECT_ROOT}/configs/gitlab-runner/config/gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}