version: '3'
services:
  zentao:
      image: harbor.jucce.cn/god/zentao:latest
      container_name: ZentaoApplication
      restart: always
      environment:
        ADMINER_USER: "mark"
        ADMINER_PASSWD:
        BIND_ADDRESS: "false"
        VIRTUAL_HOST: zentao.jucce.cn
        VIRTUAL_NETWORK: webproxy
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: zentao.jucce.cn
        LETSENCRYPT_EMAIL: juccexu@gmail.com
      ports:
        - 8085:80
        - 3085:3306
      volumes:
        - ${PROJECT_ROOT}/configs/zentao/data/zbox/:/opt/zbox/
networks:
  default:
    external:
      name: ${NETWORK:-webproxy}