version: '3'
services:
  web:
    image: 'harbor.jucce.cn/god/gitlab-ce:1.0'
    restart: always
    hostname: ${GITLABHOST}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "${GITLABEXTRAL}"
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - "8929:${GITLABPORT}"
      - "2224:22"

    volumes:
      - ${PROJECT_ROOT}/configs/gitlab/config:/etc/gitlab
      - ${PROJECT_ROOT}/configs/gitlab/logs:/var/log/gitlab
      - ${PROJECT_ROOT}/configs/gitlab/data:/var/opt/gitlab
networks:
  default:
    external:
      name: ${NETWORK:-webproxy}