version: '3'
services:
  web:
    image: 'harbor.jucce.cn/god/gitlab-ce:1.0'
    restart: always
    hostname: ${GITLABHOST}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
      VIRTUAL_HOST: gitlab.jucce.cn
      VIRTUAL_NETWORK: ${NETWORK:-webproxy}
      VIRTUAL_PORT: ${GITLABPORT}
      LETSENCRYPT_HOST: gitlab.jucce.cn
      LETSENCRYPT_EMAIL: juccexu@gmail.com
    ports:
      - '8929:80'
      - '2224:22'
    volumes:
      - ${PROJECT_ROOT}/configs/gitlab/config:/etc/gitlab
      - ${PROJECT_ROOT}/configs/gitlab/logs:/var/log/gitlab
      - ${PROJECT_ROOT}/configs/gitlab/data:/var/opt/gitlab
networks:
  default:
    external:
      name: ${NETWORK:-webproxy}