version: '3'
services:
  #PHP Service
  php-fpm:
    build:
      context: ${PROJECT_ROOT}/docker/Dockfile/php-fpm
      dockerfile: Dockerfile
    image: juccexu/php-fpm
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ${PROJECT_CODE}:/var/www
      - ${PROJECT_ROOT}/configs/php-fpm/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ${PROJECT_ROOT}/configs/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ${PROJECT_ROOT}/configs/php-fpm/php-fpm.d:/usr/local/etc/php-fpm.d
      - ${PROJECT_ROOT}/configs/php-fpm/php.ini-development:/usr/local/etc/php/php.ini-development
      - ${PROJECT_ROOT}/configs/php-fpm/php.ini-production:/usr/local/etc/php/php.ini-production
#Docker Networks
networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
