version: '3'
services:
  #Nginx Service
  webserver:
    build:
      context: ${PROJECT_ROOT}/docker/Dockfile/nginx
      dockerfile: Dockerfile
    image: juccexu/nginx
    #image: nginx:alpine
    container_name: ${NGINX_GET_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - "90:80"
      - "91:9091"
      - "92:9092"
      - "93:9093"
      - "94:9094"
      - "490:443"
    volumes:
      - ${PROJECT_CODE}:/var/www
      - ${PROJECT_ROOT}/configs/nginx/conf.d:/etc/nginx/conf.d
      - ${PROJECT_ROOT}/configs/nginx/nginx.conf:/etc/nginx/nginx.conf
#Docker Networks
networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
