version: '3'
services:
  #Nginx Service
  webserver:
    image: harbor.jucce.cn/god/nginx:1.0
    container_name: ${NGINX_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - "90:80"
      - "91:9091"
      - "92:9092"
      - "93:9093"
      - "490:443"
    volumes:
      - ${PROJECT_CODE}:/var/www
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env
#Docker Networks
networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
