version: '3'
services:
  redis:
    image: harbor.jucce.cn/god/redis:latest
    container_name: redis
    restart: always                                                                   # 指定容器退出后的重启策略为始终重启
    command: redis-server --requirepass 123456 --appendonly yes # 启动redis服务并添加密码为：123456,并开启redis持久化配置
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:                            # 数据卷挂载路径设置,将本机目录映射到容器目录
      - ${PROJECT_ROOT}/configs/redis/data:/data
    ports:
      - "6379:6379"
  redis-commander:
    image: harbor.jucce.cn/god/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=test1:redis:6379:0:123456
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
      #- REDIS_PASSWORD=123456
    ports:
      - 8081:8081
    depends_on:
      - redis
      #Docker Networks
networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
